### ISSUE TITLE
Cannot Load Compressed Strips 

### ISSUE THREAD

**Issue by mmvih** [PolusAI/bfio#1]
The full array is not loaded when the reading the image that is compressed into strips.  
It does not throw an error that the format of the image is incorrect. 

Image.shape is (512, 512, 1, 1, 1). 
My code that has worked for other images using bfio
```
# Read the input images used for testing
for im in range(num_images):
   image = os.path.join(image_dir_test, X_val[im])
   br_image = BioReader(image, max_workers=1)
   im_array = br_image[:,:,0:1,0:1,0:1]
   im_array = im_array.reshape(br_image.shape[:2])
```

Images used https://osf.io/z89pq/

The image using `skimage.io()` to read the image: 
[<img width="469" alt="Screen Shot 2021-04-27 at 12 23 15 PM" src="https://user-images.githubusercontent.com/43178933/116277362-67c4b180-a753-11eb-8960-d43e7eae0f7e.png">
](url)

The image using `bfio.read()` to read the image:
<img width="472" alt="Screen Shot 2021-04-27 at 12 19 12 PM" src="https://user-images.githubusercontent.com/43178933/116276822-e2410180-a752-11eb-971b-50d89d3cd03b.png">

The information regarding the original image when opening in ImageJ. 
<img width="438" alt="Screen Shot 2021-04-27 at 11 00 15 AM" src="https://user-images.githubusercontent.com/43178933/116277647-af4b3d80-a753-11eb-9ea4-994a4f264dfb.png">

**Comment by Nicholas-Schaub** [comment]
This should be resolved with PR #2 . The code should now throw an error when trying to use the Python backend to load the Tiff image.
