### ISSUE TITLE
Selection of image series or sub-resolutions by bioformats backend?

### ISSUE THREAD

**Issue by NHPatterson** [PolusAI/bfio#11]
After experimenting with `BioReader` with a few different vendor images, it appears the java backend defaults to the loading the first `series` in the OME metadata. For some formats this works, for instance, .czi's first series is generally scene#1, but unfortunately, it would not be possible to select scene#2 in a multi-scene image (scenes being non-contiguous image areas).  Other vendor formats, unfortunately, put a label or macro image as series#1 so this is what `BioReader` loads by default. Here is an .scn file from a Leica slide scanner which has this issue (the macro image pyramid occupies the first 3 series). 

https://drive.google.com/file/d/1a3GINDHdTY3-8f7WXcARkfXSrEWqM-Px/view?usp=sharing

Besides this, I wonder if you have a roadmap to access sub-resolutions of the pyramidal images via bioformats? Typically these are just different "series" within the metadata as well. I'll try and have a look myself as well.

**Comment by sameeul** [comment]
Fixed in v2.3.4. We can do something like the following now:
```
        with bfio.BioReader(file_path, level=1) as br:
            get_dims(br)
```
By not passing `level`, the constructor assumes it to be 0 and returns the reader handle for the top level image. If requested `level` is not found, the constructor will raise a `ValueError`.
