### ISSUE TITLE
consider splitting napari plugin into new package?

### ISSUE THREAD

**Issue by tlambert03** [PolusAI/bfio#37]
now that `aicsimageio` depends on bfio, whenever someone just installs napari and napari-aicsimageio, they always have to make a choice between aicsimageio and bfio whenever dropping a file into the viewer (though they might not even have known they installed bfio).  perhaps a separate `napari-bfio` package could be made for those specifically wanting to use the bfio variant of the napari plugin?

**Comment by sameeul** [comment]
Fixed in version 2.3.1.
