### ISSUE TITLE
Outdated call to ome_types.from_xml

### ISSUE THREAD

**Issue by anntzer** [PolusAI/bfio#39]
The calls to from_xml at https://github.com/PolusAI/bfio/blob/75c588d60cec3cdfc0a24886acd90c89a0703be6/bfio/backends.py#L436-L451 now emit a warning ("The default XML parser will be changing...") due to https://github.com/tlambert03/ome-types/blob/7f8e0011234645698d260a4e53a327afa9d6155e/src/ome_types/_convenience.py#L53-L62
Also note that the `validate=True` lines can also be uncommented now (since ome_types 0.3.0, I think).

**Comment by Nicholas-Schaub** [comment]
This has been resolved in #41
