### ISSUE TITLE
TiffBytesOffsets incompatible with tifffile.TiffFrame after tifffile 2022.4.22

### ISSUE THREAD

**Issue by BrianWhitneyAI** [PolusAI/bfio#42]
https://github.com/PolusAI/bfio/blob/75c588d60cec3cdfc0a24886acd90c89a0703be6/bfio/backends.py#L463 attempts to set self.index of tifffile.TiffFrame but new versions of tifffile.TiffFrame has the @final definition "cannot be overridden, and decorated class cannot be subclassed." [here](https://github.com/cgohlke/tifffile/blob/84c9c41668173965fdeb2907bfb42d037bf0cd00/tifffile/tifffile.py#L10045)

**Comment by sameeul** [comment]
@BrianWhitneyAI : I have been working on a fix for this issue. Do you have any multi-channel tiled OME TIff data that you can share to test the fix? The ones available in the OME site are smaller than 1024 px in X and Y dim, so this particular part of the code does not get executed.
